# This is a config for E2B sandbox template.
# You can use template ID (vcb0huedkh75r2v8ttb9) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vcb0huedkh75r2v8ttb9") # Sync sandbox
# sandbox = await AsyncSandbox.create("vcb0huedkh75r2v8ttb9") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vcb0huedkh75r2v8ttb9')

team_id = "24c03df0-edc5-4bf0-9ee9-19e4150efd44"
dockerfile = "e2b.Dockerfile"
template_id = "vcb0huedkh75r2v8ttb9"
